project_name: golog
builds:
  skip: true

changelog:
  # Set it to true if you wish to skip the changelog generation.
  # This may result in an empty release notes on GitHub/GitLab/Gitea.
  disable: false
  use: github
  sort: asc

  groups:
    - title: "Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: "Improvements"
      regexp: "^.*improv[(\\w)]*:+.*$"
      order: 3
    - title: "Refactor"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 4
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 5
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 6
    - title: "Deps"
      regexp: ^.*?deps?(\(.+\))??!?:.+$
      order: 7
    - title: "Others"
      order: 999


