on:
  push:
    branches:
      - feat/**
      - fix/**
      - improv/**
      - chore/**
      - refactor/**
      - bugfix/**

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Validate Go format and vet
        run: |
          go fmt ./...
          go vet ./...

      - name: Run tests
        run: |
          go test -v ./...

      - name: Run lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

      - name: Check for gosec
        uses: securego/gosec@master
        with:
          args: ./...